In [1]:
import numpy as np

a = np.array([[0, 1, 2, 3],  # 行列
              [1, 2, 3, 4],
              [2, 3, 4, 5]])
print(a)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


In [2]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]])
b = np.array([[2, 1],
              [2, 1],
              [2, 1]])

c = np.dot(a, b)  # 行列積
print(c)

d=np.dot(b,a)
print(d)

[[ 6  3]
 [12  6]]
[[1 4 7]
 [1 4 7]
 [1 4 7]]


In [ ]:
import numpy as np

# 入力:3 ニューロン:2
x = np.array([[0, 0.5, 1.0]])  # 入力
w = np.array([[-1, 1],  # 重み
              [1, -1],
              [-1, 1]])

print(np.dot(x, w))  # 入力と重みの積の総和

[[-0.5  0.5]]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.T)  # 転置

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]])  # 2x3の行列
b = np.array([[0, 1, 2],
              [1, 2, 3]])  # 2x3の行列 このままでは行列積ができない

# print(np.dot(a, b))  # 転置しないで行列積をとるとエラー
print(np.dot(a, b.T))  # 転置により行列積が可能に

[[ 5  8]
 [ 8 14]]
