In [1]:
!pip install numpy==2.0.2

In [2]:
import numpy as np

In [9]:
# 配列のパターン
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a + b)
print(a*2)

[11 22 33]
[2 4 6]


In [7]:
# リストのパターン
# a = [1, 2, 3]
# b = [10, 20, 30]
# print(a + b)
# print(a*2)

[1, 2, 3, 10, 20, 30]
[1, 2, 3, 1, 2, 3]


In [12]:
a[1]
a[:2]

array([1, 2])

In [16]:
# 統計量計算

a = np.array([1, 2, 3, 4, 5])
np.sum(a)
np.mean(a)
np.median(a)
np.std(a)

np.float64(1.4142135623730951)

In [17]:
# 多次元配列

A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
A.shape

(3, 2)

In [21]:
A.T.shape

(2, 3)

In [22]:
# 実際の例
scores = np.array([80, 90, 75, 100])

mean = np.mean(scores)
scores - mean

array([ -6.25,   3.75, -11.25,  13.75])

In [27]:
# 配列の作成
np.random.rand(3, 2)
np.zeros((3, 2))
np.arange(0, 100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])