In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3])

In [3]:
arr1

array([1, 2, 3])

In [4]:
arr2=np.array([4,5,6])

In [5]:
arr1+arr2

array([5, 7, 9])

In [10]:
arry3=np.array([[1,2],[3,4],[5,6]])

In [11]:
arry3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
arry3.shape

(3, 2)

In [13]:
arry3.shape[0]

3

In [14]:
arry4=np.arange(10)

In [15]:
arry4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
arry3.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.empty([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.randn(3,3) #平均値０、標準偏差１の正規分布の乱数

array([[ 0.33543291, -0.50406617,  0.25701324],
       [-0.74429178, -0.95687774,  0.50561693],
       [ 0.78468907, -0.8902536 ,  0.21575602]])

---

In [31]:
arry_x=np.arange(9).reshape(3,3)
arry_y=np.arange(9).reshape(3,3)
arry_x+arry_y

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [32]:
arry_x*arry_y

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])