In [1]:
import numpy as np

In [2]:
arr1=np.arange(9)

In [3]:
3*arr1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [7]:
arr1+1 #ブロードキャスト関数

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sin(arr1) #ユニバーサル関数

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [6]:
np.exp(arr1) #ユニバーサル関数

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03])