In [27]:
import numpy as np

In [29]:
x=np.arange(0,10)

In [31]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
y=x

In [35]:
y[1:4]=10

In [37]:
x

array([ 0, 10, 10, 10,  4,  5,  6,  7,  8,  9])

In [39]:
y[:]=5

In [41]:
x

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

---

In [48]:
import numpy as np
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [53]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [63]:
A=np.random.randn(10)

In [65]:
rng = np.random.default_rng()
B=rng.standard_normal(10)

In [67]:
np.add(A,B)

array([ 0.11207074,  0.20698943, -1.63242936, -0.22690597, -1.25281925,
       -1.38268989,  0.7611891 ,  1.93564325, -0.0038426 , -0.65566807])

In [69]:
np.maximum(A,B)

array([ 0.83222397,  0.8995017 , -0.72657743,  0.28599396, -0.14500793,
       -0.58855267,  0.84112378,  1.33453313,  0.00357103,  0.77039868])